### ISSUE TITLE
Mettre à jour l'image Docker à chaque release

### ISSUE THREAD

**Issue by raphodn** [elefan-grenoble/observatoire_produits#12]
### Quoi ?

Actuellement on stock l'image Docker sur notre Docker Hub, mais c'est une action manuelle + peu de gens ont les droits.

Idée d'automatiser cette étape à chaque changement sur la branche `main`

### Comment ?

https://github.com/docker/build-push-action

**Comment by raphodn** [comment]
Essayé sans succès : avoir la CI qui tourne + le bon tag
```
on:
  release:
    types: [published]

on:
  release:
    types:
      - published
    branches:
      - main

on:
  push:
    branches:
      - main
    tags:
      - v*.*.*
```

- https://github.com/orgs/community/discussions/25281
- https://github.com/orgs/community/discussions/26686#discussioncomment-3396593

**Comment by raphodn** [comment]
@petitalb du coup j'ai essayé plein de configs, je n'arrive pas à avoir 
- qu'au moment d'une nouvelle release (et donc d'un nouveau tag)
- ca push 2 images docker sur Docker Hub : latest & la version taggé

on:release ne marche pas car la release est créé par un workflow, donc un autre workflow ne peut pas s'en servir (cf [cette discussion](https://github.com/orgs/community/discussions/26686#discussioncomment-3396593))

on:push:branches/tags marche à moitié, mais le `github.ref_name` renvoi `main` au lieu de la version du tag (ex : `0.2.1`). c'est surement la piste la plus proche !

**Comment by petitalb** [comment]
> on:push:branches/tags marche à moitié, mais le `github.ref_name` renvoi `main` au lieu de la version du tag (ex : `0.2.1`). c'est surement la piste la plus proche !

Je n'y connais rien côté Github action (à la différence de gitlab). Je pense que l'event considéré dans ton cas est le push d'une branche. C'est ce qui explique que `github.ref_name` renvoi `main`.

A la place si tu essayes :
```
on:
  push:
    tags:
      - v*.*.*
```
Ca marche mieux ?
